### ISSUE TITLE
Can't access pannel after a fresh installation

### ISSUE THREAD

**Issue by franckadil** [andreapollastri/cipi#116]
After a fresh Install I can't access the pannel.

In the terminal I see the following exception `Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [1045] Access denied for user 'dbuser'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = dbname and table_name = smtps and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667|         // If an exception occurs when attempting to run a query, we'll format the error
    668|         // message to include the bindings with SQL, which will make this exception a
    669|         // lot more helpful to the developer instead of just the database's errors.
    670|         catch (Exception $e) {
  > 671|             throw new QueryException(
    672|                 $query, $this->prepareBindings($bindings), $e
    673|             );
    674|         }
    675|

      +15 vendor frames 
  16  app/Providers/SMTPConfigServiceProvider.php:27
      Illuminate\Support\Facades\Facade::__callStatic()

      +7 vendor frames 
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

rpl: Replacing "DB_USERNAME=dbuser" with "DB_USERNAME=junglewp" (ignoring case; whole words only)
.
rpl: could not guess encoding; using locale default 'UTF-8'

```

**Comment by franckadil** [comment]
Update: I had to manually restart the VPS (using Ubuntu 20.04 LTS)
But now I am having trouble accessing through ssh.

**Comment by andreapollastri** [comment]
Hello @franckadil,
I'm sorry to hear this issue from you but the error snippet that you posted here confirms that you aren't using original Cipi installation script but a custom so I don't know what that script does and I think that you didn't create "junglewp" database user.
Cipi creates and works with root / cipi user not with that custom jungle wp user that I think you created with an original installation file customization. 
So... I can't help you with it... if you want use Cipi autoinstall file you have to take it as it is because of it was tested and if you have any issue I can help you but if you made a custom installation script I can't help you with it.
If you want customize your Cipi installation you can manage it as a classic laravel project (follow readme.md to discover how to install it with composer-create project), so you can change db info or other file.

About the SSH error... Cipi by default disables root login for secrity reasons but supplies to you an alternative sudo access in the finale screen of autoinstallation file, here you are it:
````
#FINAL MESSAGGE
clear
echo "***********************************************************"
echo "                    SETUP COMPLETE"
echo "***********************************************************"
echo ""
echo "Use $REMOTE to manage your server."
echo ""
echo "If you need SSH into this server:"
echo "Cipi SSH username: $USER"
echo "Cipi SSH password: $PASS"
echo "Cipi MySql root/cipi pass: $DBPASS"
echo ""
echo "***********************************************************"
echo "          DO NOT LOSE AND KEEP SAFE THIS DATA"
echo "***********************************************************"
````
If you log with "cipi" secondary user you can than grant root access using "sudo -su" command.

**Comment by franckadil** [comment]
@andreapollastri Thank you for your reply :) I edited the installation script and changed the user.
No pressure, I am just testing, the app I hope I can bring valuable feedback and contribution in the future. (I noticed you're looking for help with the documentation as an example).

To get back to the error reported here, please note that the panel worked only after restarting the VM, I tried with both versions of the scripts for 20.04. The original with "cipi" user and mine with "junglewp".

Regards,

**Comment by andreapollastri** [comment]
Hi @franckadil! Thankyoou for the feedback! No pressure (sorry if my bad english looks rude) :-P 
I think that the problem is that you didn't create a "root" user customizing the script so every thing was broken but I don't know what happened so I prefer suggest to you to use original script.
About help on project everything is welcome... I'm pubblishing the Documentation and it will be ready soon... if you would correct something in it you are very welcome! It will be stored here: https://github.com/andreapollastri/cipi.sh

I'm happy for you interest in Cipi... I hope that you can use it without issue and with great results.

Best,
Andrea

**Comment by franckadil** [comment]
@andreapollastri Don't worry about it, and let me congratulate you for your awesome work! I've seen the commits since few days and I have to admit that's triggered my attention. I'll be more than happy to contribute, and put in the effort required to help. I'll keep testing for now.

**Comment by andreapollastri** [comment]
Great! I hope to hear from you soon! Best! Andrea
