### ISSUE TITLE
Auto fix White Screen of Death

### ISSUE THREAD

**Issue by JFOC** [andreapollastri/cipi#127]
hi,
It would be nice to have auto fixing the White Screen of Death for Wordpress sites.

**Comment by andreapollastri** [comment]
Hi! Tell me more about this problem! I would fix it but I can't replicate it! WP works fine by my Side on Cipi and I have no 500 errors... Thank You!

**Comment by MilenFrom** [comment]
Show us the error logs?
White screen of death may not be related to the panel itself?

**Comment by JFOC** [comment]
we do not have any error currently, but the feature is nice to have.
this is a feature I have in my current panel and my control panel is designed for WP
<img width="844" alt="Screen Shot 2020-07-01 at 14 23 00" src="https://user-images.githubusercontent.com/240271/86215167-77608180-bba6-11ea-8b20-29973f24aa45.png">

**Comment by MilenFrom** [comment]
Hmm, basically when a WP install returns Fatal error to notify you?
Basically this goes through all plugins and disables each one of them until the parse error is gone.

This might go wild, meaning turning off your plugins might output shortcodes content in your page which may have negative impact.

So what can be done actually is to place maintenance page until you fix the issue, because php parse error can be triggered by many things specially in WP...

Just my 2 cents

**Comment by JFOC** [comment]
it goes to enhancement instead of help-wanted label

**Comment by andreapollastri** [comment]
Ok perfect! I will evaluate it for the next release!
