### ISSUE TITLE
Frontend UI

### ISSUE THREAD

**Issue by shumtz** [andreapollastri/cipi#193]
Hi! Me again ... I'm testing Cipi, but I've been thinking about improving the user interface (Dashboard, login pages and more).

I can help with that.

**Comment by techieshark** [comment]
@shumtz could you post a screenshot? I'm considering using cipi but haven't had chance  to set it up yet (so I'm curious what it looks like currently).

**Comment by shumtz** [comment]
Yes! Images here: https://imgur.com/a/4y8MK4K.

I am writing a new user interface. I'm using Cipi in development mode (localhost), the server is more complete.

**Comment by shumtz** [comment]
There are more settings on the server in production.

**Comment by techieshark** [comment]
Thanks @shumtz!

**Comment by techieshark** [comment]
OK, I've just been able to test this locally using [Vagrant](vagrantup.com/) + [Virtualbox](https://www.virtualbox.org/) (config details below).

Some UX thoughts:

1. when it first loads a page called "Dashboard", it is blank and I'm like "ok what do I do now?". So maybe there could be some "welcome to Cipi, here are the docs and here's what you might do to get started..." to cover that blank area.

2. On the "Servers" page (http://localhost:9080/servers), it has two buttons that are a bit confusing:

![image](https://user-images.githubusercontent.com/1072292/114107440-5dfa1c00-9914-11eb-8fb9-def8560389c4.png)

I wonder, "what is it waiting for?". Perhaps there is some background process that has hung (maybe because I'm running locally and its normal provisioning scripts are failing? e.g. SSL provisioning? I don't know... so maybe some display of important logs would help).

Also, does "delete" just delete what I installed with Cipi? Maybe it should be called "destroy" instead? Maybe it could explain what that button does. Also it is greyed out (disabled), and I wonder why (maybe it could tell me?).

On page "Sites", perhaps because cipi hasn't finished, I see I cannot make a new site because I have no server.

![image](https://user-images.githubusercontent.com/1072292/114107919-4707f980-9915-11eb-8efb-be397d26e3ee.png)

I'm also not sure what "basepath" means... is that the directory inside `/var/www` where the site will be placed?

That's all I could test for now. Hopefully these comments might help with improving the UI. It seems like quite a nice project.

## Vagrant setup

1. mkdir cipi && cd cipi
2. copy/paste into a new file, "Vagrantfile"
```
# Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 9080
  config.vm.network "forwarded_port", guest: 443, host: 9443
  # fix virtualbox slow wifi on Mac https://serverfault.com/a/595010
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
```
3. `vagrant up`
4. `vagrant ssh`
5.  (Now inside the virutal box): `wget -O cipi.sh https://cipi.sh/go.sh && sudo ./cipi.sh`

**Comment by shumtz** [comment]
Wow, awesome! Thank You for all suggestions. I'm working on the UI, I'm going to apply some suggestions that you made. Thanks.

My fork for updates.
https://github.com/shumtz/cipi

**Comment by techieshark** [comment]
Possibly some other inspiration here - https://github.com/coollabsio/coolify#screenshots

**Comment by shumtz** [comment]
In "dashboard" exist components for ram usage, cpu e etc... Maybe need installation Cipi 100% to work.

![screenshot](https://prnt.sc/117tb56)

I will change it, make the components visible in all situations...

I'll be back with some changes and news.

**Comment by shumtz** [comment]
Link for image: https://prnt.sc/117tb56

**Comment by shumtz** [comment]
Maybe this for dashboard page...

![Captura de tela 2021-04-09 002306](https://user-images.githubusercontent.com/44671356/114124086-ff0fb500-98c9-11eb-9079-f906b7b8af09.png)

For more information and details in page.

**Comment by shumtz** [comment]
Maybe this for footer in sidebar.

![Captura de tela 2021-04-09 002922](https://user-images.githubusercontent.com/44671356/114124354-a55bba80-98ca-11eb-9499-f059fa396478.png)

More visibility for the user...

**Comment by techieshark** [comment]
+1 for putting CPU/Mem/Disk usage in sidebar (would they update in real time?)

**Comment by andreapollastri** [comment]
Hi @shumtz ... Thank you for your idea... I'm a backend dev... not frontend so an help is welcome :) but there is some problem with your design:
- Cipi manages more than 1 server so in dashboard I have to visualize more "tabs"... sidebar is not enough
- I don't want to show "update news" in dashboard because IMHO are not important and they will be not so "frequently" updated

**Comment by shumtz** [comment]
It's true... I didn't pay attention to this specific detail. 

I need to work at the moment. Later on I will develop a design to work on all servers. I'll be back with more ideas and changes.

Thanks

**Comment by johnnestebann** [comment]
Hey guys, i'm a full stack software developer, with laravel/symfony and vue/angular/bootstrap experience, and sysadmin too. I really would like to help with the project (back and front). I was designing mobile-friendly/desktop dashboards and interfaces based on bootstrap 5 like this 

![image](https://user-images.githubusercontent.com/25795363/116682079-2ebf5380-a984-11eb-97e1-5c8ef4b285f3.png)

It was developed with Laravel, Livewire and Bootstrap 5.
I'm using hestiacp and vestacp for all my web projects, so i'm glad to help you develop this laravel option.
i'll do some implementations and will show some screenshots
