### ISSUE TITLE
There was a problem with server connection. Try later!

### ISSUE THREAD

**Issue by zietbukuel** [andreapollastri/cipi#21]
This happened after a fresh Ubuntu 18.04 LTS installation. I tried to add a new Application and I get this error every time. Help?

**Comment by andreapollastri** [comment]
Are you working on the same VPS or are you using Cipi to deploy other VPSs?

**Comment by zietbukuel** [comment]
I'm trying to deploy another VPS.

**Comment by andreapollastri** [comment]
Ok! Let me investigate on it. What VPS provider are you using to do it?

**Comment by zietbukuel** [comment]
Hi, I use Digital Ocean.

**Comment by andreapollastri** [comment]
Hi! Currently I've no problem with DO standard Ubuntu 18.04 TLS servers.

**Comment by zietbukuel** [comment]
Weird, I've tried again with a different server and I got the same message.

**Comment by andreapollastri** [comment]
Ok... I'll re-check now and I'll response to you soon!

**Comment by andreapollastri** [comment]
I checked it now in:
- Digital Ocean
- Vultr
- AWS
- Azure
- Enter.it

And I've no any problem!
I'm so sorry! 

THE LAST INSTALLATION WITHOUT PROBLEM IS HERE:
Server: http://68.183.2.248/
Client: http://167.71.79.78/

I close this issue!

**Comment by LewisSmallwood** [comment]
One of my servers is also experiencing the same problem as I am using Key-based authentication for SSH. 

If enabled, DigitalOcean will configure your server automatically using SSH keys, this is probably the reason you were experiencing issues @zietbukuel 

Because the control panel is requiring passwords that are auto-generated for the servers during the setup process, this is causing issues. This fails on line `$ssh = New \phpseclib\Net\SSH2($server->ip, $server->port);` line of the `ApplicationsController`. 

Turning off key-based authentication will fix the issue.
