### ISSUE TITLE
Upgrade v2 to v3?

### ISSUE THREAD

**Issue by magix01** [andreapollastri/cipi#227]
Is it possible to upgrade v2 to v3 without loosing servers or functionality?

**Comment by andreapollastri** [comment]
Hi @magix01  sorry for the late reply... currently no. I'm working on this feature but I don't have an ETA yet!
It's no so simple and Ubuntu 18.04 is not yet supported by Cipi v3. And there are also problems within PHP7.2 and MySql 5.7 so I think that it would be not possible... nut I'm working on it... since v3, every update will be compatible with future versions!
