### ISSUE TITLE
Generating username from domain name could be better

### ISSUE THREAD

**Issue by fatihalp** [andreapollastri/cipi#362]
I'm making lots of changes from ssh console. Then it's hard to change working directory when you have random generated usernames. 

like:

`$site->username   =  substr ( strtolower($request->domain), 0, 8 );`

What do you think?

**Comment by andreapollastri** [comment]
Hi! Thank You for the issue!

Cipi was made thinking to a different use than your massive Editing of sites configuration so I'm sorry if the usernames will take slow your process.

Anyway, your idea could not be considered because:

- username has to be unique and a domain trim is not unique (you could have similar domains)

- username is absolute and it can't be changed, domain is relative to username and it could be changed via panel

- for these reasons your idea can't be implemented to avoid conflicts in Linux users

- the last topic is "security"... Cipi generates secure and "logic unlinked" usernames for your sites, this will improve your VPS security!

**Comment by fatihalp** [comment]
First of all, there may be a one in a billion duplicate in the current situation :)

I was thinking same way you about security. I realized that user experience is more important than anything else.
 I really liked project even I was thinking start same kind of project and you already did it which is same logic with me. 

![image](https://user-images.githubusercontent.com/219454/148958708-0e33364c-b265-4f31-a3b5-95fb924c5d2e.png)
cPanel has market share of 94.30% in web-hosting-control-panel market. If cPanel solved these issues I believe we can. Maybe it's not time to do that I understand. 
 
There is a monopoly in the control panel industry and unfair pricing. I really want the project to go forward.

**Comment by andreapollastri** [comment]
Hi, you are right, cPanel and Plesk let to customize username and password but I really don't like this approach and I think that user experience is very important but security is most important than anything else.

Anyway, about UI, personally I like the concept of:
- automatic isolation of users
- autogenerated "anonymus" credentials
so everyone can create a secure site with Cipi in a few clicks without taking care about passwords complexity or other bullshit stuff.

I'm really sorry about my answer but Cipi is an Open Source project so feel free to customize it to your needs.

Best,
Andrea
