### ISSUE TITLE
sites added in cipi not created on server

### ISSUE THREAD

**Issue by rkmaier** [andreapollastri/cipi#371]
I manged to add my first site using the cpanel in CIPI, but none of the other sites  I added after that are created on the server and I don't see any error messages.

**Comment by andreapollastri** [comment]
Do you receive any error? Are you sure that vuoi does not create any virtual host after the first? It's really illogical this behavior! Give me more details about this issue! (Provider, how are you checking the issue, ...)

**Comment by rkmaier** [comment]
Hi, well the site details are added to cipi database but the user for the new site is not created (no new user folder created), so I couldn't connect to it using ssh.  Im using a dev domain, which requires ssl by default, maybe that's the issue.

**Comment by andreapollastri** [comment]
oK! It's very strange! By my Side this version of cipi has no problem in user creation but that step is complex... the steps are:

- creating user in db
- creating a job that will connect in ssh to your server run:
- user creation, virtual host creation

So the problems could be:
- supervisor for the jobs
- ssh connection (firewall, credentials, ...)
- other

I don't have access to your current situation and it's very strange!

Try to give me:
/var/www/html/storage/logs/laravel.log 

And to check if in main cipi db is there any failed job In failed_jobs table.

Check also if you have any firewall for ssh and that ports 22,80 and 443 are open... than for devs domain click on generate ssl because cert it's the only way to view a .dev website!

**Comment by Donniewr** [comment]
I had the same issue, the problem was the the permissions in`/var/www/html ` Check the permissions of that folder.

https://github.com/andreapollastri/cipi/issues/347

**Comment by rkmaier** [comment]
@andreapollastri  Checked the jobs, it shows them as processed but the new site is not created. 
No error in the laravel log file. 
Ports seem fine. 

I tried to run the commands froms the NewSite Job manually and this is what I get:
`unlink: cannot unlink 'newsite': No such file or directory`
