### ISSUE TITLE
Issues Installing the gRPC extension

### ISSUE THREAD

**Issue by ausittechdirect** [andreapollastri/cipi#373]
Hi 

Trying to install the gRPC google PHP extension how can I do this?

**Comment by andreapollastri** [comment]
Hi! 
This PHP extension does not come by default so you have to log into SSH as root (cipi) and follow this tutorial: https://grpc.io/docs/languages/php/basics/.

No official Cipi support for this library!

**Comment by ausittechdirect** [comment]
Hi Andrea

I have looked at this but it seems to want to install into the wrong directory.

Is there somewhere specific I need to compile it?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ausittechdirect** [comment]
Just reading your message and see you say (cipi) do I have to make this change on the main CIPI server or do I do this on the node server that servers the site?

**Comment by ausittechdirect** [comment]
Can I possible Pay you to implement this for me?

**Comment by andreapollastri** [comment]
Hi, sorry but I don't have time to support and manage custom implementations. Anyway, I don't know that product and I never used it so I'm not expert about its integration so I can't sell to you something that I can just try to do but without guarantees.

About the server... you have to install it into the server (main or node) that hosts the site with the application that needs the extension.

I'm really sorry but I can't help you in this issue because this functionality is not related to Cipi.

**Comment by ausittechdirect** [comment]
Ok Cool 
Appreciate your honesty.
