### ISSUE TITLE
New site is not created on servers

### ISSUE THREAD

**Issue by rkmaier** [andreapollastri/cipi#374]
#371 

@andreapollastri  Checked the jobs, it shows them as processed but the new site is not created. 
No error in the laravel log file. 
Ports seem fine. 

I tried to run the commands froms the NewSite Job manually and this is what I get:
`unlink: cannot unlink 'newsite': No such file or directory`

**Comment by andreapollastri** [comment]
Hi! This issue is related to Issue #371!

I'm sorry but I have no elements to help you! It's very strange your situation and I can't replicate it in my server because cipi works correctly! 

Anyway you cannot run a job manually without any data payload so the error that you have got during debug is ok! 

Give me more information... what provider are you using that I try to install cipi there? 
What's the flow that you are doing to manage your sites? 

I checked Cipi and it works and if you have not failed jobs or unprocessed jobs or error logs I can't help you because there are no errors in the system! Help me to replicate your situation in my own Cipi so I could help you!

**Comment by rkmaier** [comment]
Hi, 

I'm using Hetzner as Provider for my servers.

**Comment by andreapollastri** [comment]
Ok! I have installed on the same provider a brand new version of Cipi and I have no issues within sites! Please help me to help you! I can't replicate your error so by my side Cipi is ok, I don't know the flow and the situation that gives you errors! Sorry!
